@superAdminAuth = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNTE0MjNkZDgxMDVmOTFkNDNiNTU3OCIsInJvbGUiOiJndWVzdCIsImlhdCI6MTY0OTQ5MjU0MSwiZXhwIjoxNjQ5NTE0MTQxfQ.889YwhfbvTJ34apnqk9fG3cS25bFUte5_x0NrfjD7q4

@token =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0Y2FlOGJhZGI2OWZkNzNmZDdiZGMyNSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNjkxMDk2NzU3LCJleHAiOjE2OTExMTgzNTd9.0ZFiJjOkTDsnJI0kKx0b5njln8cH8vC2l9lvlaJb3CM

@token2 =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNTk5OTNjYzc1MmQzY2QxMjViOTQyYSIsInJvbGUiOiJndWVzdCIsImlhdCI6MTY1MDAzOTEwMCwiZXhwIjoxNjUwMDYwNzAwfQ.n45mcBfTXqoXgUpbso7s6gnBDk3EjxgjqwKsxByJoCI

 
### Add Business
POST {{$dotenv CLIENT_SERVER_URL}}/business/create HTTP/1.1
Authorization: bearer {{token}}
content-type: application/json 

{
    "BusinessName": "Business Name",
    "description": "Business Description",
    "location": 
    {
        "lng":0,
        "lat":0
    },
    "address": "Business Address",
    "email": "Businesdsqqaqqaqwqeeaaaqqss Email",
    "phone": "Business Phone",
    "userId": "64c7003633be3a0b83d5548d"
}

### Get Business
POST {{$dotenv CLIENT_SERVER_URL}}/business/getMyBusiness HTTP/1.1
Authorization: bearer {{token}}
content-type: application/json

{
    "userId": "64cae8badb69fd73fd7bdc25"
}
