@token =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0Y2FlOGJhZGI2OWZkNzNmZDdiZGMyNSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNjkxMDk2NzU3LCJleHAiOjE2OTExMTgzNTd9.0ZFiJjOkTDsnJI0kKx0b5njln8cH8vC2l9lvlaJb3CM






### add product
POST {{$dotenv CLIENT_SERVER_URL}}/menu/AddProduct HTTP/1.1
Authorization: bearer {{token}}
content-type: application/json 

{
  "products": [
    {
      "ProductName": "expresso",
      "description": "coffee description",
      "prices": [
        {
          "price": 5,
          "size": "standard",
          "category": "coffee"
        }
      ]
    },
    {
      "ProductName": "cappuccino",
      "description": "description",
      "prices": [
        {
          "price": 7,
          "size": "standard",
          "category": "coffee"
        }
      ]
    },
    {
      "ProductName": "maricana",
      "description": "my 1 menu description",
      "prices": [
        {
          "price": 9,
          "size": "standard",
          "category": "coffee"
        }
      ]
    }
  ],
  "menuId": "64cae9bd9647ab96277288d4"
}




### create menu
POST {{$dotenv CLIENT_SERVER_URL}}/menu/create HTTP/1.1
Authorization: bearer {{token}}
content-type: application/json 

{
    "MenuName": "my 1 menu",
    "description": "my 1 menu description",
    "businessId": "64cae9a59647ab96277288d0"
}

### get menu
POST {{$dotenv CLIENT_SERVER_URL}}/menu/getMyMenus HTTP/1.1
Authorization: bearer {{token}}
content-type: application/json

{
    "businessId": "64cae9a59647ab96277288d0"
}

### get my business
POST {{$dotenv CLIENT_SERVER_URL}}/business/getMyBusiness HTTP/1.1
Authorization: bearer {{token}}
content-type: application/json

{
    "userId": "64cae9a59647ab96277288d0"
}

