@token =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0YzcwMDM2MzNiZTNhMGI4M2Q1NTQ4ZCIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNjkxMDIyMjI5LCJleHAiOjE2OTEwNDM4Mjl9.zSJfVg_jX9CiTvcinhEeoRtecfUDEBZN4GCILLhqjgo






### add product
POST {{$dotenv CLIENT_SERVER_URL}}/menu/AddProduct HTTP/1.1
Authorization: bearer {{token}}
content-type: application/json 

{
  "products": [
    {
      "ProductName": "expresso",
      "description": "coffee description",
      "prices": [
        {
          "price": 5,
          "size": "standard",
          "category": "coffee"
        }
      ]
    },
    {
      "ProductName": "cappuccino",
      "description": "description",
      "prices": [
        {
          "price": 7,
          "size": "standard",
          "category": "coffee"
        }
      ]
    },
    {
      "ProductName": "maricana",
      "description": "my 1 menu description",
      "prices": [
        {
          "price": 9,
          "size": "standard",
          "category": "coffee"
        }
      ]
    }
  ],
  "menuId": "64c7bfd29b39e0928005ccfe"
}



### create menu
POST {{$dotenv CLIENT_SERVER_URL}}/menu/create HTTP/1.1
Authorization: bearer {{token}}
content-type: application/json 

{
    "MenuName": "my 1 menu",
    "description": "my 1 menu description",
    "businessId": "64c7bccf769c75f273b75999"
}