@token =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0YzcwMDM2MzNiZTNhMGI4M2Q1NTQ4ZCIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNjkwODEyMDE2LCJleHAiOjE2OTA4MzM2MTZ9.P-GV5Dth3Kx8rxBnqCG4V-FnNHoVQ3J2BjOeVmvE8xg






### add product
POST {{$dotenv CLIENT_SERVER_URL}}/order/place-order HTTP/1.1
Authorization: bearer {{token}}
content-type: application/json 

{
    "businessId": "64c7bd2c1dcb0e65d2d66b05",
    "tableNumber": 14,
    "products": [{
        "price": 100,
        "size": "small",
        "category": "Drinks"
    }]
}
